version: "3"

services:
  canjes-bd:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - "33062:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: CANJES